version: '3.9'
name: 'url-shortener'

services:
  postgresql:
    image: postgres:16-bookworm
    hostname: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: url-shortener
      POSTGRES_PASSWORD: url-shortener@123
  redis:
    image: redis:7.2-alpine3.19
    restart: always
    ports:
      - '6379:6379'
#    environment:

  url-shortener-api:
    image: felipebraga/url-shortener:latest
    build:
      context: .
      args:
        - BUILDPLATFORM=arm64
      dockerfile: Dockerfile
    hostname: url-shortener-api
    profiles:
      - local-dev
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres
    depends_on:
      - postgresql
      - redis
