version: '3.9'
name: 'url-shortener-multi'

services:
  shortener_1:
    image: url-shortener:latest
    hostname: shortener-1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/url-shortener
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  shortener_2:
    image: url-shortener:latest
    hostname: shortener-2
    depends_on:
      - postgres_db
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/url-shortener
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shortener_1
      - shortener_2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  postgres_db:
    image: postgres:16-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: url-shortener
      POSTGRES_PASSWORD: url-shortener@123
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'